import { Inter } from 'next/font/google'
import './globals.css'
import Sidebar from "./component/Sidebar/sidebar"
import Header from "./component/Header/header"
// import Dashboard from "./component/Dashboard/dashboard"
import '@/app/component/Main/main.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Sidebar></Sidebar>
        <Header></Header>
      
        {children}
      
      </body>
    </html>
  )
}
